### ISSUE TITLE
Fake support for Ruby 3

### ISSUE THREAD

**Issue by OrelSokolov** [hanami/router#218]
When using ruby 3.0.2

```
NoMethodError: undefined method `unescape' for URI:Module
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/http_router-0.11.2/lib/http_router/request.rb:10:in `initialize'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/http_router-0.11.2/lib/http_router.rb:283:in `new'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/http_router-0.11.2/lib/http_router.rb:283:in `raw_call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/hanami-router-1.3.2/lib/hanami/routing/http_router.rb:160:in `raw_call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/hanami-router-1.3.2/lib/hanami/router.rb:1019:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/lint.rb:50:in `_call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/lint.rb:38:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/show_exceptions.rb:23:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/content_length.rb:17:in `call'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/rack-2.2.3/lib/rack/handler/webrick.rb:95:in `service'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/webrick-1.7.0/lib/webrick/httpserver.rb:140:in `service'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/webrick-1.7.0/lib/webrick/httpserver.rb:96:in `run'
        /home/oleg/.rvm/gems/ruby-3.0.2/gems/webrick-1.7.0/lib/webrick/server.rb:310:in `block in start_thread'
127.0.0.1 - - [16/Feb/2022:18:39:03 +0300] "GET / HTTP/1.1" 500 55448 0.0063

```

Steps to reproduce:

Create any dummy application, for example like this:
```ruby
require "hanami/router"

app = Hanami::Router.new do
  get "/", to: ->(env) { [200, {}, ["Welcome to Hanami!"]] }
end

run app
```

**Comment by cllns** [comment]
@OrelSokolov You're using `hanami-router` v1.3.2, which only supports Ruby 2.x. That's because it's relies on the abandoned `http_router` gem, which doesn't support Ruby 3.

`hanami-router` was completely rewritten for v2. It's only had alpha releases so far, but it's quite stable and you can use it with Ruby 3. Just specify `v2.0.0.alpha6` as the version in your Gemfile

Closing, but feel free to re-open if you have issues with Ruby 3 and `hanami-router` v2

**Comment by OrelSokolov** [comment]
@cllns ok, add note in README please
