### ISSUE TITLE
hanami routes fails when Sinatra app mounted in container

### ISSUE THREAD

**Issue by cyphactor** [hanami/router#92]
It seems in the scenario where you have a Container architecture hanami app and have a Sinatra app mounted it blows up with an exception because the inspector assumes a `Hanami::Router` instance. I discovered this because I was mounting Sidekiq's web interface into my hanami container application as follows:

```ruby
Hanami::Container.configure do
  mount Sidekiq::Web, at: '/sidekiq'
end

```

The following is the traceback. I believe it would potentially be as simple as checking if the router responds to `inspector` and if it doesn't ignore it.

```text
/Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/routes_inspector.rb:213:in `inspect_router': undefined method `inspector' for #<Hash:0x007ff13b607780> (NoMethodError)
Did you mean?  inspect
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/routes_inspector.rb:163:in `block in inspect_routes'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/routes_inspector.rb:161:in `each'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/routes_inspector.rb:161:in `inspect_routes'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-router-0.6.2/lib/hanami/routing/routes_inspector.rb:139:in `to_s'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/commands/routes.rb:25:in `start'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/lib/hanami/cli.rb:103:in `routes'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/adeponte/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hanami-0.7.2/bin/hanami:5:in `<top (required)>'
	from /Users/adeponte/.rbenv/versions/2.3.0/bin/hanami:23:in `load'
	from /Users/adeponte/.rbenv/versions/2.3.0/bin/hanami:23:in `<main>'

```

**Comment by cyphactor** [comment]
After further digging maybe I am wrong about the solution. Maybe it is a problem with the identification of it being a `nested_router` as seen in the calling method below:

```ruby
      def inspect_routes(formatter, base_path)
        result = ''

        # TODO refactoring: replace conditional with polymorphism
        # We're exposing too much knowledge from Routing::Route:
        # #path_for_generation and #base_path
        @routes.each do |route|
          result << if router = route.nested_router
            inspect_router(formatter, router, route, base_path)
          else
            inspect_route(formatter, route, base_path)
          end
        end

        result
      end
```

**Comment by cyphactor** [comment]
Yeah, after further digging I am more convinced of the latter as it is even described in the description of the `router.nested_router` method as seen below.

```ruby
      # Introspect the given route to understand if there is a wrapped
      # Hanami::Router
      #
      # @since 0.2.0
      # @api private
      def nested_router
        dest.routes if dest.respond_to?(:routes)
      end
```

So the intent of the `nested_router` method is to identify if there is a wrapped `Hanami::Router`. In this case there is a wrapped Sinatra application that happens to respond to `routes` but returns a hash representation rather than a `Hanami::Router`.
